### ISSUE TITLE
数据发布时间问题

### ISSUE THREAD

**Issue by yuanshengjun** [syuoni/eznlp#23]
你好 看您论文：A Unified Framework of Medical Information Annotation and Extraction for Chinese Clinical Text 受益匪浅，非常感谢。
在论文中，有提到会发布相关数据，请问是预计什么时候发布呢。
For researchers, we provide a benchmark to evaluate their information extraction algorithms. The corpus is from real EMRs, and carefully annotated by experienced physicians, covering a range of medical departments and EMR sections.

**Comment by syuoni** [comment]
你好。数据会在论文发表后公开，谢谢关注。

**Comment by syuoni** [comment]
您好，HwaMei-500 已经公开。

https://github.com/syuoni/eznlp/blob/master/publications/framework/HwaMei-500.md

**Comment by syuoni** [comment]
您好，HwaMei-500 已经公开。

https://github.com/syuoni/eznlp/blob/master/publications/framework/HwaMei-500.md
