### ISSUE TITLE
HwaMei-500

### ISSUE THREAD

**Issue by weinixuehao** [syuoni/eznlp#24]
Where is the dataset of HwaMei-500?

**Comment by syuoni** [comment]
Hi, 
Our paper is currently in a preprint version. The dataset will be released upon the acceptance of the paper. 
Thanks

**Comment by yhl111** [comment]
请问现在可以下载HwaMei-500数据集了嘛，想复现一下论文中的实验

> Hi, Our paper is currently in a preprint version. The dataset will be released upon the acceptance of the paper. Thanks

**Comment by syuoni** [comment]
Hi, 

HwaMei-500 has been released. Please check: https://github.com/syuoni/eznlp/blob/master/publications/framework/HwaMei-500.md

**Comment by hammerLgr** [comment]
> Hi,
> 
> HwaMei-500 has been released. Please check: https://github.com/syuoni/eznlp/blob/master/publications/framework/HwaMei-500.md

The link (http://47.99.121.158:8000/)in this article is not avalible. It has new link now? 
Thanks
