### ISSUE TITLE
ERROR: ResolutionImpossible

### ISSUE THREAD

**Issue by henrywang0314** [syuoni/eznlp#25]
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of eznlp to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install eznlp and eznlp==0.2.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    eznlp 0.2.0 depends on transformers==4.3.2
    allennlp 2.0.1 depends on transformers<4.3 and >=4.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

**Comment by syuoni** [comment]
This issue is the conflict of versions between `allennlp` and `transformers`. 

From scratch, you may first install `pytorch` and `torchvision` by conda like:
```
$ conda install pytorch==1.7.1 torchvision==0.8.2 torchtext==0.8.1 -c pytorch
```

Then manually install the following packages:
```
$ pip install flair==0.7
$ pip install allennlp==2.0.1
$ pip install transformers==4.3.2
$ pip install jieba==0.42.1
$ pip install hanziconv==0.3.2
$ pip install truecase==0.0.12
$ pip install openpyxl
$ pip install pandas 
$ pip install eznlp --no-deps
```

**Comment by syuoni** [comment]
We have updated the README file for this issue
