### ISSUE TITLE
how to process the ACE2005 data in "ace-lu2015emnlp"

### ISSUE THREAD

**Issue by cai-yuxiang** [syuoni/eznlp#31]
Hi, I have the original ACE2005 dataset. But I found it's hard to process them to "*.data". I
read the code in your paper "Joint mention extraction and classification with mention hypergraphs" which is mentioned in the your paper. I could not find the code about processing. If you can tell me a clear way, I would appreciate it. Thanks and regards.

**Comment by syuoni** [comment]
Hi, 

The ACE 2005 dataset used in the "boundary smoothing" paper was directly acquired from the authors of Lu and Roth (2015, EMNLP). 

You can also send an email to the authors for the dataset; or, I can send you a copy if you show me your licence of the original ACE 2005 data. I have sent you an email. 

Enwei

**Comment by Heihaierr** [comment]
> Hi,
> 
> The ACE 2005 dataset used in the "boundary smoothing" paper was directly acquired from the authors of Lu and Roth (2015, EMNLP).
> 
> You can also send an email to the authors for the dataset; or, I can send you a copy if you show me your licence of the original ACE 2005 data. I have sent you an email.
> 
> Enwei

Hi, I meet the same question. I've got the licence, can you send me a copy of ACE 2005 data. Thanks and regards.

**Comment by syuoni** [comment]
> > Hi,
> > The ACE 2005 dataset used in the "boundary smoothing" paper was directly acquired from the authors of Lu and Roth (2015, EMNLP).
> > You can also send an email to the authors for the dataset; or, I can send you a copy if you show me your licence of the original ACE 2005 data. I have sent you an email.
> > Enwei
> 
> Hi, I meet the same question. I've got the licence, can you send me a copy of ACE 2005 data. Thanks and regards.

I cannot find your email address. Please first send me an email to show your licence (e.g., screenshot or a copy of the original ace05 dataset).

**Comment by Tsukiaa** [comment]
> 嗨，我有原始的 ACE2005 数据集。但我发现很难将它们处理为“*.data”。我阅读了您的论文“联合提及提取和分类与提及超图”中的代码，该代码在您的论文中提到。我找不到有关处理的代码。如果你能告诉我一个明确的方法，我将不胜感激。谢谢和问候。

你好，方便分享一下ACE2005的原始数据集吗？

**Comment by syuoni** [comment]
Hi all, 

Because of licence issues, we authors cannot directly share the ACE data to others. Please: 
* Get the licence of data from LDC (non-free); 
* Send an email to me (my email adress is on my homepage) or the authors of Lu and Roth (2015, EMNLP) to show that *you have the original ACE data*. 

Thanks

***
各位，

因为数据许可原因，我们无法直接将 ACE 数据分享给大家。请：
* 从 LDC 获取数据使用许可（收费）；
* 发送一封邮件给我（邮箱地址在我的主页）或者 Lu and Roth (2015, EMNLP) 的作者，证明你拥有数据使用许可。

谢谢

**Comment by syuoni** [comment]
> 

我并没有收到你的邮件，请从我的主页找到邮箱地址并发送邮件给我，谢谢！

另外，请不要直接将你的 licence 截图发到公共平台上。

**Comment by syuoni** [comment]
> Here is the screenshot. Thanks! | | Bohao Liu | | ***@***.*** | On 3/14/2023 19:45，Enwei ***@***.***> wrote： Hi, The ACE 2005 dataset used in the "boundary smoothing" paper was directly acquired from the authors of Lu and Roth (2015, EMNLP). You can also send an email to the authors for the dataset; or, I can send you a copy if you show me your licence of the original ACE 2005 data. I have sent you an email. Enwei Hi, I meet the same question. I've got the licence, can you send me a copy of ACE 2005 data. Thanks and regards. I cannot find your email address. Please first send me an email to show your licence (e.g., screenshot or a copy of the original ace05 dataset). — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

我并没有收到你的邮件，请从我的主页找到邮箱地址并发送邮件给我，谢谢！

另外，请不要直接将你的 licence 截图发到公共平台上。

**Comment by syuoni** [comment]
> 

即使如此，我也不确定这样的操作是否完全没有法律风险。这已经是我们作为作者能做到的极限了，请各位谅解，谢谢。

**Comment by Heihaierr** [comment]
> > Here is the screenshot. Thanks! | | Bohao Liu | | _**@**_.*** | On 3/14/2023 19:45，Enwei _**@**_._**> wrote： Hi, The ACE 2005 dataset used in the "boundary smoothing" paper was directly acquired from the authors of Lu and Roth (2015, EMNLP). You can also send an email to the authors for the dataset; or, I can send you a copy if you show me your licence of the original ACE 2005 data. I have sent you an email. Enwei Hi, I meet the same question. I've got the licence, can you send me a copy of ACE 2005 data. Thanks and regards. I cannot find your email address. Please first send me an email to show your licence (e.g., screenshot or a copy of the original ace05 dataset). — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.**_>
> 
> 我并没有收到你的邮件，请从我的主页找到邮箱地址并发送邮件给我，谢谢！
> 
> 另外，请不要直接将你的 licence 截图发到公共平台上。

你好，我已将licence截图重新发到你的邮箱enwei.zhu@outlook.com，请注意确认。非常感谢提醒和分享！
