### ISSUE TITLE
请问用Flair进行embedding时的flair/news-forward-0.4.1.pt与flair/news-backward-0.4.1.pt这两个文件从哪里获取？

### ISSUE THREAD

**Issue by ldsheng1998** [syuoni/eznlp#38]

**Comment by syuoni** [comment]
参考 Flair 项目中 https://github.com/flairNLP/flair/blob/16fbbbd3f7978dfb1b5d13d8b9005e3401f1448c/flair/embeddings/token.py#L556C17-L556C17 ，可以知道所有模型的下载链接。

所以，你需要的模型文件链接为：
* https://flair.informatik.hu-berlin.de/resources/embeddings/flair/news-forward-0.4.1.pt
* https://flair.informatik.hu-berlin.de/resources/embeddings/flair/news-backward-0.4.1.pt

**Comment by ldsheng1998** [comment]
> 参考Flair项目中https://github.com/flairNLP/flair/blob/16fbbbd3f7978dfb1b5d13d8b9005e3401f1448c/flair/embeddings/token.py#L556C17-L556C17，可以知道所有模型的下载链接。
> 
> 所以，你需要的模型文件链接为：
> 
> * https://flair.informatik.hu-berlin.de/resources/embeddings/flair/news-forward-0.4.1.pt
> * https://flair.informatik.hu-berlin.de/resources/embeddings/flair/news-backward-0.4.1.pt

非常感谢您！
