### ISSUE TITLE
您好，现在我运行的您的eznlp代码的F1值过低，想请教您一些问题，您方便留个联系方式吗

### ISSUE THREAD

**Issue by cyx9898010** [syuoni/eznlp#44]
我使用的数据集是根据您代码中的demo处理后的，只有49%的F1值，您有空的话可以给我的邮箱留个言吗，我的邮箱是phantom159357@outlook.com，如果方便的话，还想找您拿一下您当时运行的数据集

**Comment by syuoni** [comment]
请问具体是哪个数据集？如果是 ACE 04/05 的话，请参考：https://github.com/syuoni/eznlp/issues/31#issuecomment-1471266399

可以直接发邮件给我：enwei.zhu@outlook.com
