### ISSUE TITLE
调用decode

### ISSUE THREAD

**Issue by houyuchao** [syuoni/eznlp#51]
作者您好，我想请教一下我想在entity_recognition主程序中，调用BoundarySelectionDecoder类中的decode方法，但是缺乏non label，我无法在主程序对应到BoundarySelectionDecoder类中的config参数，有什么办法吗？
![image](https://github.com/syuoni/eznlp/assets/162104094/62668ee4-3381-4f1d-8ba4-57030e9bcb76)
![image](https://github.com/syuoni/eznlp/assets/162104094/b3cb877b-c709-4a97-8490-a2f7245fbda6)

**Comment by syuoni** [comment]
`entity_recognition.py` 里调用 boundary smoothing 的代码在这里：https://github.com/syuoni/eznlp/blob/master/scripts/entity_recognition.py#L244-L259

请参考代码原本的使用方法进行修改。你的代码片段中 `args` 是不能传入 `BoundarySelectionDecoder` 的。
