### ISSUE TITLE
The ground truth yij 

### ISSUE THREAD

**Issue by houyuchao** [syuoni/eznlp#52]
The ground truth yij 指的是代码中的non mask吗
![image](https://github.com/syuoni/eznlp/assets/162104094/59255a64-46f1-46f9-a130-c7e267143ae2)

**Comment by houyuchao** [comment]
论文中提到的yij
![image](https://github.com/syuoni/eznlp/assets/162104094/92ae9bf4-041c-4e68-8ee7-0c34fa6813f8)

**Comment by syuoni** [comment]
`label_ids` 是 ground truth y_{ij}。`non_mask` 是用于确定哪些位置为 padding 的一个 mask tensor。

**Comment by houyuchao** [comment]
> `label_ids` 是 ground truth y_{ij}。`non_mask` 是用于确定哪些位置为 padding 的一个 mask tensor。

谢谢
