### ISSUE TITLE
将剩余概率分配给非实体

### ISSUE THREAD

**Issue by houyuchao** [syuoni/eznlp#54]
![image](https://github.com/user-attachments/assets/63f1569a-f6b4-49e1-aa47-9a1075d72a82)
出现这种情况的时候就需要像论文说的那样把剩余概率分配给非实体部分是吧，对应的代码就是

**Comment by houyuchao** [comment]
> ![image](https://private-user-images.githubusercontent.com/162104094/348442062-63f1569a-f6b4-49e1-aa47-9a1075d72a82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4MzU4MTAsIm5iZiI6MTcyMDgzNTUxMCwicGF0aCI6Ii8xNjIxMDQwOTQvMzQ4NDQyMDYyLTYzZjE1NjlhLWY2YjQtNDllMS1hYTQ3LTlhMTA3NWQ3MmE4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxM1QwMTUxNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTZhODU1NTRmZmU4NmFhOGVmYjExODc0OTQ4MWI1NTgzYTY2N2Q4NTQyODU5NDQ5MTk3YzUwNTRkY2EyY2E2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Oq4a-gBuTZ_Mfyb2bjEkiH1JZdHcwtinmLaOvV028Xk) 出现这种情况的时候就需要像论文说的那样把剩余概率分配给非实体部分是吧，对应的代码就是

![image](https://github.com/user-attachments/assets/9bd14c26-767b-4464-86cc-9630604992cb)

**Comment by syuoni** [comment]
> > ![image](https://private-user-images.githubusercontent.com/162104094/348442062-63f1569a-f6b4-49e1-aa47-9a1075d72a82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4MzU4MTAsIm5iZiI6MTcyMDgzNTUxMCwicGF0aCI6Ii8xNjIxMDQwOTQvMzQ4NDQyMDYyLTYzZjE1NjlhLWY2YjQtNDllMS1hYTQ3LTlhMTA3NWQ3MmE4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxM1QwMTUxNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTZhODU1NTRmZmU4NmFhOGVmYjExODc0OTQ4MWI1NTgzYTY2N2Q4NTQyODU5NDQ5MTk3YzUwNTRkY2EyY2E2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Oq4a-gBuTZ_Mfyb2bjEkiH1JZdHcwtinmLaOvV028Xk) 出现这种情况的时候就需要像论文说的那样把剩余概率分配给非实体部分是吧，对应的代码就是
> 
> ![image](https://private-user-images.githubusercontent.com/162104094/348442118-9bd14c26-767b-4464-86cc-9630604992cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0OTM0OTAsIm5iZiI6MTczMzQ5MzE5MCwicGF0aCI6Ii8xNjIxMDQwOTQvMzQ4NDQyMTE4LTliZDE0YzI2LTc2N2ItNDQ2NC04NmNjLTk2MzA2MDQ5OTJjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQxMzUzMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzJjZGJhMWJmODI3ZDdkZjQ0YThlMTdiZmFlMjhhMzhiM2E4ZGNlMDE1YjllODdlZmE1MWEyY2MwNDAwYmY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2oph-mBxdVS-pBE6YYdRktiBn2ZSQbDiVhdkk_mL0d0)

是的，就是这部分代码。

**Comment by Huyangjuan** [comment]
> > ![image](https://private-user-images.githubusercontent.com/162104094/348442062-63f1569a-f6b4-49e1-aa47-9a1075d72a82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4MzU4MTAsIm5iZiI6MTcyMDgzNTUxMCwicGF0aCI6Ii8xNjIxMDQwOTQvMzQ4NDQyMDYyLTYzZjE1NjlhLWY2YjQtNDllMS1hYTQ3LTlhMTA3NWQ3MmE4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxM1QwMTUxNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTZhODU1NTRmZmU4NmFhOGVmYjExODc0OTQ4MWI1NTgzYTY2N2Q4NTQyODU5NDQ5MTk3YzUwNTRkY2EyY2E2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Oq4a-gBuTZ_Mfyb2bjEkiH1JZdHcwtinmLaOvV028Xk) 出现这种情况的时候就需要像论文说的那样把剩余概率分配给非实体部分是吧，对应的代码就是
> 
> ![image](https://private-user-images.githubusercontent.com/162104094/348442118-9bd14c26-767b-4464-86cc-9630604992cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MjA4NDAsIm5iZiI6MTczMzgyMDU0MCwicGF0aCI6Ii8xNjIxMDQwOTQvMzQ4NDQyMTE4LTliZDE0YzI2LTc2N2ItNDQ2NC04NmNjLTk2MzA2MDQ5OTJjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQwODQ5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZmRlMGI0Y2U1YzEzMDYyMTkyODE1Mzc0NDRmYmMxMzk5N2Q4N2ZjM2UyNWRiYjcxZjRjNjUxOThmZTU1ZTIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.V3BoWB-Ag8JbqrpWMXzbtNFLPZUXZD1spkmmkG0DGXc)

请问您能知道这部分的none_idx是什么意思嘛，怎么得来的

**Comment by syuoni** [comment]
`none_idx` 就是代表非实体的 index，也就是 none_label 的 index。参考：https://github.com/syuoni/eznlp/blob/master/eznlp/model/decoder/boundary_selection.py#L124

**Comment by Huyangjuan** [comment]
> `none_idx` 就是代表非实体的 index，也就是 none_label 的 index。参考：https://github.com/syuoni/eznlp/blob/master/eznlp/model/decoder/boundary_selection.py#L124

谢谢您的回复，请问这个none_idx不要的话会对构建边界平滑的那个矩阵造成什么影响嘛

**Comment by syuoni** [comment]
如果没有 `none_idx`，更直接的问题是，如何处理非实体的片段呢？

**Comment by Huyangjuan** [comment]
> 如果没有 `none_idx`，更直接的问题是，如何处理非实体的片段呢？

因为我看self.label_ids = torch.zeros(self.num_tokens, self.num_tokens, config.voc_dim, dtype=torch.float)这行代码好像在构造矩阵的时候，就已经自动将非实体的部分构造成0了，这不是构造的全0矩阵嘛，后面只需要把实体部分加上概率

**Comment by syuoni** [comment]
请看这行代码：https://github.com/syuoni/eznlp/blob/master/eznlp/model/decoder/boundaries.py#L185
