### ISSUE TITLE
没找到如论文所说使用softmax计算预测值

### ISSUE THREAD

**Issue by houyuchao** [syuoni/eznlp#60]
您好请问这是计算预测值的代码吧？怎么没看到论文所说的softmax呢？？
![image](https://github.com/user-attachments/assets/9f87f119-f199-4fc9-b8e1-5cf8d926f67a)

**Comment by syuoni** [comment]
softmax 在计算 loss 的时候会计算。比如 boundary smoothing 的 loss 计算中涉及 softmax 的代码是这里：https://github.com/syuoni/eznlp/blob/master/eznlp/nn/functional.py#L203
