### ISSUE TITLE
encode部分

### ISSUE THREAD

**Issue by houyuchao** [syuoni/eznlp#62]
您好请问代码中的encode部分在哪里啊

**Comment by syuoni** [comment]
Encode 部分基本就是对 BERT/RoBERTa 做了一个简单的封装，参考：https://github.com/syuoni/eznlp/blob/master/eznlp/model/bert_like.py

我发现你提了好些关于“xx功能的代码在哪”的问题，推荐使用 Python pdb 工具做断点调试，一般都能很快找到代码执行的逻辑。
