### ISSUE TITLE
MSRA数据集

### ISSUE THREAD

**Issue by houyuchao** [syuoni/eznlp#63]
您好我想复现一下论文中MSRA数据集的结果，可以分享一下MSRA预处理的代码吗？万分 感谢

**Comment by lanyangyang93** [comment]
哈哈哈  SIGHAN 2006  [scripts/utils.py#L304]  @houyuchao

**Comment by lanyangyang93** [comment]
哈哈哈 SIGHAN 2006 [scripts/utils.py#L304] @houyuchao  百度一下你会发现 MSRA-NER (SIGHAN2006)

**Comment by syuoni** [comment]
请参考论文对应的[文档](https://github.com/syuoni/eznlp/blob/master/docs/boundary-smoothing.md)，谢谢！

**Comment by lanyangyang93** [comment]
您的邮件我已经收到，谢谢
