### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by houyuchao** [syuoni/eznlp#66]
作者您好，可以提供医学的这个数据集吗
![image](https://github.com/user-attachments/assets/b428b213-cfcd-46ce-bfc7-f020f62aa35a)

**Comment by syuoni** [comment]
请参考文档：https://github.com/syuoni/eznlp/blob/master/publications/framework/HwaMei-500.md

论文的所有作者都已经从原单位离职，所以数据的 link 已经没有维护了。但还是可以给这个文档中的邮箱发邮件，谢谢！ cc @lanyangyang93

**Comment by houyuchao** [comment]
> 请参考文档：https://github.com/syuoni/eznlp/blob/master/publications/framework/HwaMei-500.md
> 
> 论文的所有作者都已经从原单位离职，所以数据的 link 已经没有维护了。但还是可以给这个文档中的邮箱发邮件，谢谢！ cc @lanyangyang93

非常感谢，我已经获得了数据集如图，但是遇到了这样的问题，这是由于预处理的方式与数据集格式不匹配吗？
![image](https://github.com/user-attachments/assets/0524169f-518f-4b39-9065-08bef6bb33a3)
![image](https://github.com/user-attachments/assets/e09b20cc-584d-4be2-a473-5f089cb4c72b)
![image](https://github.com/user-attachments/assets/ff9027a2-e1a7-48d1-b235-ce2d64e4bde2)

**Comment by houyuchao** [comment]
> 请参考文档：https://github.com/syuoni/eznlp/blob/master/publications/framework/HwaMei-500.md
> 
> 论文的所有作者都已经从原单位离职，所以数据的 link 已经没有维护了。但还是可以给这个文档中的邮箱发邮件，谢谢！ cc @lanyangyang93

非常感谢我获得了数据集，但是更换之后为什么训练的时候会变成这样呢？？？10s训练了40轮
![image](https://github.com/user-attachments/assets/e69b2862-c61d-4c6e-aa7e-2615c02ef195)

**Comment by houyuchao** [comment]
> > 请参考文档：https://github.com/syuoni/eznlp/blob/master/publications/framework/HwaMei-500.md
> > 论文的所有作者都已经从原单位离职，所以数据的 link 已经没有维护了。但还是可以给这个文档中的邮箱发邮件，谢谢！ cc @lanyangyang93
> 
> 非常感谢我获得了数据集，但是更换之后为什么训练的时候会变成这样呢？？？10s训练了40轮 ![image](https://private-user-images.githubusercontent.com/162104094/394768351-e69b2862-c61d-4c6e-aa7e-2615c02ef195.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MjQ4MDYsIm5iZiI6MTczMzkyNDUwNiwicGF0aCI6Ii8xNjIxMDQwOTQvMzk0NzY4MzUxLWU2OWIyODYyLWM2MWQtNGM2ZS1hYTdlLTI2MTVjMDJlZjE5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQxMzQxNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMWM1MjE3NmQxZGE4OTE5NmU2MTUxMzU0ZDcyMjViMjQ2OWRhOWIyYzkwYTk2NzcyZTg5Njc3NGUwOGFhODQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EzLEmVBHtCZqLtrFYgl_-EZ4ZBNPnTpvsNILBN-orLY)

是不是还是我数据预处理或者数据集有问题呢？？
![image](https://github.com/user-attachments/assets/29af7bad-f7f0-4ee0-a96f-ab95bae47e80)

**Comment by syuoni** [comment]
看 log 只读取了一条数据。还是请你多尝试断点调试，这些问题在你本地环境里调试起来都是相对容易的，谢谢！

**Comment by syuoni** [comment]
另外，如果问题得到解决了，请及时关闭 issue。谢谢！

**Comment by Huyangjuan** [comment]
> 作者您好，可以提供医学的这个数据集吗 ![image](https://github.com/user-attachments/assets/b428b213-cfcd-46ce-bfc7-f020f62aa35a)

您好，请问您有成功复现这个数据集嘛

**Comment by lanyangyang93** [comment]
您的邮件我已经收到，谢谢
